### PR TITLE
Adding a snapshot type that can be extended

### PR DESCRIPTION
**Pull request by nikunjy**

### CODE REVIEW

**Comment by nikunjy** [comment]
What do you think @rcrowley @mihasya

**Comment by nikunjy** [comment]
Is this repository dead ?

**Comment by mihasya** [comment]
Not quite dead, but it's unfortunately not currently part of anybody's full-time job to monitor it. As a result, things go in fits and starts. The time commitment to review something is extended by having to context switch into a repo I don't think about regularly. Sorry about this, I'll try to find time to review the PR soon.

**Comment by nikunjy** [comment]
The tests will have to change a little bit because I am introducing a new type. Instead of returning won types Snapshot() returns a type of Snapshot() and Snapshot is a read copy.
The tests don't have any significant change.

**Comment by nikunjy** [comment]
Closing it as I don't think I will merge it.

**Pull request closed without merging**
