### PR TITLE
Implementation of distribution metric

### PR DESCRIPTION
**Pull request by SubChord**
This distribution metrics is in essence an histogram with customizable buckets.

This gives us the freedom to define our own buckets in stead of the predefined percentiles.

### CODE REVIEW

**Comment by SubChord** [comment]
Implemented new type: Vector-Counter 

It is a collection of Counters as found in prometheus.
Support for prometheus was implemented as well in: https://github.com/deathowl/go-metrics-prometheus/pull/15

**Comment by SubChord** [comment]
@rcrowley any plans on accepting PRs?

**Comment by keithknott26** [comment]
Yes, it would be great if this were merged in I'm looking to use it for a project i'm working on

**Comment by deathowl** [comment]
@rcrowley  any interest in mergint this so I can merge https://github.com/deathowl/go-metrics-prometheus/pull/15 ?

**Comment by deathowl** [comment]
@mihasya  i see you took over ownership. Could you take a look at this?

**Pull request closed without merging**
