### PR TITLE
Replace lock with CAS in standard meter stop

### LINKED ISSUE #245: Data race between StandardMeter Stop and Mark
The implementation of [`Stop`][1] is using a lock instead of `atomic.CompareAndSwapUint32` to serialize the `stopped` flag.  This races with the implementation of [`Mark`][2] that uses `atomic.LoadUint32` as there is no serialization guarantee between the two.

```
WARNING: DATA RACE
Write at 0x00c420312478 by goroutine 126:
  github.com/hyperledger/fabric/vendor/github.com/rcrowley/go-metrics.(*StandardMeter).Stop()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/rcrowley/go-metrics/meter.go:151 +0x6f
  github.com/hyperledger/fabric/vendor/github.com/rcrowley/go-metrics.(*StandardRegistry).stop()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/rcrowley/go-metrics/registry.go:227 +0xe4
  github.com/hyperledger/fabric/vendor/github.com/rcrowley/go-metrics.(*StandardRegistry).Unregister()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/rcrowley/go-metrics/registry.go:189 +0x8f
  github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama.(*Broker).Close()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama/broker.go:186 +0x6cc
  github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama.safeAsyncClose.func1()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama/utils.go:52 +0x70
  github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama.withRecover()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama/utils.go:45 +0x50

Previous read at 0x00c420312478 by goroutine 111:
  sync/atomic.LoadInt32()
      /opt/go/src/runtime/race_amd64.s:206 +0xb
  github.com/hyperledger/fabric/vendor/github.com/rcrowley/go-metrics.(*StandardMeter).Mark()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/rcrowley/go-metrics/meter.go:167 +0x42
  github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama.(*Broker).updateOutgoingCommunicationMetrics()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama/broker.go:878 +0x1db
  github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama.(*Broker).send()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama/broker.go:582 +0x50c
  github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama.(*Broker).sendAndReceive()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama/broker.go:601 +0x80
  github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama.(*Broker).Produce()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama/broker.go:267 +0x138
  github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama.(*asyncProducer).newBrokerProducer.func1()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama/async_producer.go:572 +0xe1
  github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama.withRecover()
      /opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/Shopify/sarama/utils.go:45 +0x50
```

[1]: https://github.com/rcrowley/go-metrics/blob/e2704e165165ec55d062f5919b4b29494e9fa790/meter.go#L149-L152
[2]: https://github.com/rcrowley/go-metrics/blob/e2704e165165ec55d062f5919b4b29494e9fa790/meter.go#L167-L169

### PR DESCRIPTION
**Pull request by sykesm**
Fixes #245

### CODE REVIEW

**Comment by tsuna** [comment]
I can confirm that this patch fixes the race.

**Comment by mihasya** [comment]
Sorry about the delay, taking a look. Going to ping @deckarep since this looks related to the work from #232. @sykesm @tsuna @deckarep is this a missed spot from that PR? If so, I'll merge right away, but want to make sure I'm not missing something first. Thanks all!

**Comment by tsuna** [comment]
Not sure what you meant by "is this a missed spot from that PR?". If you're asking whether this fixes the race, then yes it does, I can confirm from my review of the code and my CI builds with `-race` passing with it.

**Comment by mihasya** [comment]
@tsuna the linked PR switched from using mutexes to using CAS. It is my understanding that this race was likely introduced at that point because one instance of mutex was not updated. I want to confirm that my understanding is correct. I don't look at this code very frequently any more, so I want to make sure I understand where the bug comes from, lest we introduce yet another one somewhere else.

**Comment by tsuna** [comment]
One code path was using a CAS, the other a mutex, that's no bueno. Either both should use a mutex or both should use a CAS. This fix removes the mutex altogether so that only CAS is used.

**Comment by deckarep** [comment]
Let me look stand by

**Comment by deckarep** [comment]
Going off my memory, yes this is related and the change makes sense...I probably did not catch this race...I also remember attempting to leave the stop logic as is.

This fix LGTM.

**Comment by mihasya** [comment]
👏 seems like we're all on the same page.

**Pull request merged**
